"""Natural task prompts for semantic routing across the bundled Agent skills.

The expected skill name is local evaluator data. It is deliberately absent from
the prompt and from the V2 ``tool_policy.required_skills`` field so a passing
result proves semantic selection rather than answer following.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SkillRoutingCase:
    skill_name: str
    prompt: str
    discriminator: str


SKILL_ROUTING_CASES: tuple[SkillRoutingCase, ...] = (
    SkillRoutingCase(
        skill_name="village-canvas-3d-asset",
        prompt=(
            "我想把剧本里的古代机关盒做成后续能进入3D场景的资产，但还没决定用图生3D、"
            "多视角重建还是直接建模。请比较适合的工具和推荐管线，并考虑贴图、骨骼与导出"
            "格式，不要真的替我生成资产。"
        ),
        discriminator="3D资产的建模、绑定与工具链，而不是把已定人物和道具摆进三维空间。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-3d-scene-director",
        prompt=(
            "第3集茶馆对峙要预演：三个人围桌，一人起身，两把椅子在身后，门口还有"
            "围观者。请把剧情落成可执行的3D场景数据，明确站位、朝向、关节姿态、道具"
            "和机位，并给出要写入三维世界节点的完整数据；本轮先不要实际写入画布。"
        ),
        discriminator="三维坐标、关节和机位预演，而不是普通分镜文字或镜头配方。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-agent-tool-surface",
        prompt=(
            "你上一条说“任务列表返回0条”，我不确定是真的调用了工具，还是当前会话"
            "根本没挂载这个能力。请先核实当前会话工具面和产品注册证据，再给出真实"
            "回执；没有调用就不要说返回0条，也不要用终端模拟一次。"
        ),
        discriminator="会话工具面与真实回执是否成立，而不是某个生成任务为何失败。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-aigc-knowledge",
        prompt=(
            "我要给一部水墨赛博短片编译图生视频提示词，角色要身份一致，雨夜霓虹场景"
            "要锁定，还要适配不同模型支持的能力。请不要直接生成，先从项目事实和知识"
            "规则里选出相关方法，输出可执行的提示词合同与未知项。"
        ),
        discriminator="按任务路由知识并编译生成合同，而不是只做节点提示词的安全覆盖。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-canvas-commands",
        prompt=(
            "我刚写好5个分镜提示词，想把它们一次建成画布节点，按顺序连接，再移动成"
            "两列，并确保这组操作能整体撤销。请先把这批操作编译成可执行命令清单，明确"
            "顺序、引用和撤销语义；本轮不要实际写入画布，也不要启动图片或视频任务。"
        ),
        discriminator="批量结构命令、引用和撤销语义，而不是画布级导演诊断。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-canvas-director",
        prompt=(
            "我当前打开的创作画布很乱，身份、场景、几何和风格参考都混在生成节点前，"
            "还可能有孤立节点和错误连线。请基于最新画布结构判断哪些节点保留、修改、"
            "创建或连接，给出最小整理方案和每步回执要求；本轮不要实际写入画布。"
        ),
        discriminator="整张画布的职责、上下游和最小编辑顺序，而不是执行一批既定命令。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-canvas-ops",
        prompt=(
            "我想用LibTV命令行管理画布：先查图片和视频模型，再创建两个节点、上传参考图，"
            "最后下载一个已有节点的结果。请列出真实命令和参数边界，付费生成节点不要执行，"
            "先告诉我哪些会改动工作区。"
        ),
        discriminator="workspace、project、node、group和素材级CLI操作，而不是创作结构编排。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-casting-design",
        prompt=(
            "女主现在只有几段小传，我想在制作正式角色设定表之前，从三个方向比较谁更能"
            "承受从压抑到失控的戏：脸型、体态、生活痕迹和多角度辨识都要有区别。请做"
            "选角视觉判断和五轮测试设计，先不要生成正式角色资产。"
        ),
        discriminator="角色形象尚未定案前的选角决策，而不是制作正式资产或修复漂移。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-character-consistency",
        prompt=(
            "第二集开拍前我发现同一个角色在第 3 镜和第 11 镜长相明显不一样，服装细节"
            "也漂了。请给我一套跨镜头保证角色身份一致的做法：身份卡怎么建、参考图怎么"
            "锚定、服装和特写怎么锁，以及每一步怎么核验真的没换脸。先不要批量生成。"
        ),
        discriminator="跨镜头身份账本、定脸与服装锁定，而不是选角、单图试探或摄影方案。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-character-workflow",
        prompt=(
            "角色方向已经批准，我想把通过的那张全身照做成正式设定表：先单图试探并等待"
            "我审核，再用审核图生成浅灰背景的大头照加三视图，确保比例和服装一致。请按"
            "这个渐进流程设计提示词和检查点，不要跳过人工审核直接批量生成。"
        ),
        discriminator="胜出形象已定后制作正式参考资产，而不是重新选角或检查成片连续性。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-cinematography",
        prompt=(
            "这场母女争吵要从压迫慢慢走向松开，我想系统决定构图、焦段、景深、主光和"
            "机位，让摄影语言本身参与情绪变化。请给出能写进镜头提示词的摄影方案，不要"
            "替我扩展成整段分镜或直接生成画面。"
        ),
        discriminator="摄影语法本身，而不是镜头覆盖、镜间节奏或视频配方执行。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-combat-director",
        prompt=(
            "这场一对一打斗该怎么拆镜、每镜多长、哪些是打斗专有的声明字段？战损能不能"
            "回退、两个打斗者的身份怎么保持一致、台词说不完怎么办？我只要判断标准和要"
            "看的画面，不要生成媒体。"
        ),
        discriminator="打斗特有的结构、因果链、战损连续性与声明字段，而不是镜头覆盖、摄影方案或单镜配方。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-continuity",
        prompt=(
            "第2集里男主的眉疤、深灰外套和桌上蓝色药瓶在三个镜头中不断变化，左右站位"
            "也发生反转。请先找正式身份和场景锚点，逐镜标出视觉漂移与最低成本修复，只"
            "返修受影响的镜头。"
        ),
        discriminator="视觉身份、服装、道具与左右关系的一致性审计，而不是剧本事实检查。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-coverage-planner",
        prompt=(
            "这场打斗目前只有一个主镜和两个特写，动作中段断开，剪辑时没有过程、反应"
            "和手部道具插入可用。请规划可剪接的镜头覆盖，补足必要的动作预演和B-roll，"
            "并明确最少需要新增哪些素材。"
        ),
        discriminator="已有核心叙事镜头后的剪辑覆盖量和动作可接性，而不是重设故事怎么拍。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-delivery-qc",
        prompt=(
            "第一版成片已经导出，我要做正式交付质检：检查缺镜、黑帧、音画同步、字幕、"
            "角色连续性和技术规格，并按阻断、严重、建议给返工优先级。请只基于正式成片"
            "和任务合同判断，缩略图或旧预览不能当作最终验收对象。"
        ),
        discriminator="已完成成片的可交付性判断，而不是定位生成失败或研究后制工具。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-director-framework",
        prompt=(
            "我接到一部从零开始的AI短片，既有资产盘点、剧本、分镜、模型选择、积分预算"
            "和翻车返修要一起管理。请给出一套能按物理动作、镜头提示词、低清试跑和成片"
            "流程执行的总框架，不要只讲电影理论。"
        ),
        discriminator="端到端项目SOP和成本控制，而不是只补导演理论或单个镜头工艺。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-director-knowledge-base",
        prompt=(
            "我想补齐自己做AI导演的底层判断，重点是电影语言、导演思维，以及怎样把叙事"
            "意图转成视频提示词。请给能力框架和判断模型，不要输出项目执行SOP，也不要"
            "把它当成当前工具能力的证明。"
        ),
        discriminator="导演能力底座和判断逻辑，而不是从零到成片的操作框架。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-engineering-governance",
        prompt=(
            "我要修复村长 Agent 的画布回执问题，改动会跨前端、API 和 WorkflowRun，必须"
            "保证 diff 小、合同清楚、回归可复现并能回滚。请按观察、计划、干跑、实施、"
            "等待、验证、回写这套工程闭环推进，不要新建第二套状态或记忆系统。"
        ),
        discriminator="产品代码、合同与运行证据治理，而不是搭建创作管线或蒸馏新技能。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-expression-director",
        prompt=(
            "这一幕里丈夫表面平静，实际在压抑怒火，我希望他的站位、视线、呼吸、手势"
            "和对手反应都能演出潜台词。请设计完整的表演镜头合同，并给出可落到当前画布"
            "提示词的方案；本轮先不要写回画布，"
            "不要自造表情锚点，也不要把写下方案说成视频已经生成。"
        ),
        discriminator="角色目标、对手关系、潜台词和画布落地，而不是纯微表情执行。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-failure-rescue",
        prompt=(
            "昨晚启动的视频任务现在卡住了，平台提示参数不兼容，但已有成功首帧和部分"
            "配音。请先读取真实任务与错误原文，做根因分类并指出最低成本恢复点，不要从头"
            "重跑，也要说明重试是否会重复扣费。"
        ),
        discriminator="真实任务失败的诊断与恢复，而不是成片QC或静态工作流设计。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-iron-rules",
        prompt=(
            "我准备发布一组生图和视频提示词，但人物皮肤、眼睛和裙子写了很多十六进制"
            "颜色，关键词也堆得过长。请在交付前做硬性自检，删除人物色块风险并判断什么"
            "时候该精简、什么时候复杂场景要保留详细描述，不要重写成完整项目提示词。"
        ),
        discriminator="三条硬性规则的自检与例外判断，不需要通用模块编译或节点写回。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-knowledge-engine",
        prompt=(
            "我想弄明白提示词前部为什么影响更大、权重语法怎么用，以及对白场景里的声线、"
            "环境音和音画同步台词该如何组织。请解释注意力、上下文和声音设计的底层规律，"
            "并给能落到提示词的可控参数，不要启动音频生成。"
        ),
        discriminator="注意力、上下文、画布统计和声音设计的底层知识，而不是项目专用路由。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-lora-training",
        prompt=(
            "我有这个角色的二十多张剧照，想让之后的模型更稳定地还原她，但目前不知道"
            "怎么准备数据和训练。请判断图片数量与多样性是否够，规划裁切、标注、工具、"
            "参数和推理强度，不要直接说模型已经训练成功。"
        ),
        discriminator="数据集和模型微调本身，而不是叠加现成LoRA或制作角色参考图。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-method-distiller",
        prompt=(
            "上个月这个画布从一句创意一路做到成片，效果很好，我想把其中真正可复用的"
            "判断沉淀成新的内部技能。请只读节点血缘、任务记录和返工证据，区分事实与"
            "推断，并设计典型、误触发和缺输入三类评测。"
        ),
        discriminator="把真实创作流程蒸馏为可独立路由的技能，而不是修改产品代码。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-lighting-director",
        prompt=(
            "这个夜景镜头平均发亮，看不出光从哪来，人和背景糊在一起，隔壁那条街的灯"
            "还把整条街都照亮了。请只从光影这一层给我修：写清每盏光的身份、位置、受光面"
            "和衰减范围，多镜的话把跨镜头不变量也锁住。镜头和风格别动。"
        ),
        discriminator="光源层级、衰减与跨镜头光线不变量，而不是摄影语法或全片风格锁。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-music-score",
        prompt=(
            "成片已经剪完，但音乐现在只是从头铺到尾，缺少角色主题、进入退出和对白让位。"
            "请设计cue map、主题动机、歌曲或纯音乐结构以及15秒/30秒版本，并给生成模型"
            "写清楚音乐合同，不要把配乐方案说成工程混音已经通过。"
        ),
        discriminator="音乐叙事、生成合同和音画同步，而不是配音、调色或最终混音验收。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-one-click-film",
        prompt=(
            "这个项目已经有角色、分镜和部分首帧，我想从当前进度自动推进到整集成片，"
            "中途可以暂停、恢复，并保留已经成功的阶段。请先只读检查持久制作状态，"
            "给出在授权预算内继续同一个运行的推进计划；本轮不要启动或恢复任何运行。"
        ),
        discriminator="durable production run、暂停恢复和预算控制，而不是普通画布整理。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-image-prompt-craft",
        prompt=(
            "我这张图出来太脏了，背景一堆碎东西，主体也不突出，整体还灰扑扑的没颜色。"
            "请按单张成图的纪律帮我把提示词重写：一个视觉中心、减配背景、主色辅色理清，"
            "先别出图。"
        ),
        discriminator="单张图片提示词的成图质量与减配纪律，而不是分镜或视频提示词。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-performance-craft",
        prompt=(
            "这个特写里角色的“难过”只剩皱眉，脸还一跳一跳，呼吸和身体完全没有重量。"
            "请把情绪拆成眼、呼吸、重心、手部、物理反馈和起止余波，给出可以逐项复验的"
            "微表演方案，不要在缺少动机时替角色编造内心独白。"
        ),
        discriminator="已有表演方向下的微表情和物理执行问题，而不是重设完整表演导演方案。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-post-production",
        prompt=(
            "片子画面已经定了，我现在要处理配音、口型、多语言版本和统一调色，还想比较"
            "工具、成本与版权注意事项。请给后制方案和验收边界，配乐创作不要混进来，也"
            "不要把未执行的工序说成已经完成。"
        ),
        discriminator="配音、调色和口型后制，而不是音乐叙事创作或成片最终QC。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-performance-director",
        prompt=(
            "这场父女和解的戏，AI 生成出来两个角色全程面无表情地在念台词。我想让它真的像"
            "人在说话：她想要什么、什么东西挡着、没说出口的部分怎么用停顿和眼神露出来。"
            "请给角色定一份表演母版，再落到这一场，服装摄影灯光都别写进去。"
        ),
        discriminator="表演层从零设计（目标/阻碍/节拍/母版），而不是已有方向下的微表情执行。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-practical-directing-lessons",
        prompt=(
            "上一支片子六镜技术全达标但你说不出哪里不对——评价是「没啥看头」，角色"
            "表情像木偶，片尾构图还慢慢漂了，字幕烧进了画面。请用实测过的实战参数帮"
            "我逐条诊断：每镜有没有视觉事件、微表情怎么编码、首尾帧怎么锚定，以及"
            "烧字幕怎么规避。先给诊断和参数，不要直接生成。"
        ),
        discriminator="真实付费生成沉淀的实战参数补遗（视觉事件、FACS、首尾帧锚定），"
        "而不是通用导演框架或单点摄影语法。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-prompt-director",
        prompt=(
            "现在选中的图像节点提示词太笼统，上游有身份图、场景图和首帧参考。请读取"
            "节点、模型和参数的真实事实，展示完整原稿与优化稿、每项修改依据和参考职责，"
            "等我确认后再覆盖，而且优化本身不能触发生成。"
        ),
        discriminator="绑定真实节点、模型、参考职责和安全写回，而不是通用提示词模块设计。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-prompt-framework",
        prompt=(
            "我要把一段4秒视频构思编译成提示词，只放一个主体、一条主动作和一个主运镜，"
            "同时明确景别、布光和影调。请按可执行模块组织，遇到30秒或多场景内容要提示"
            "拆镜，不要机械套一个万能模板。"
        ),
        discriminator="可复用提示词结构、决策矩阵和时长拆镜，而不是节点事实读取与写回。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-script-integrity",
        prompt=(
            "这部12集短剧改了七轮，女主在第5集忽然知道前面没发生过的秘密，旧钥匙伏笔"
            "也和第8集冲突。请先建立事实账本，检查角色知识、时间线、道具和伏笔，给出"
            "最小修复与影响范围，不要直接重写剧情。"
        ),
        discriminator="多轮改写后的叙事事实与跨集一致性，而不是设计新剧情或检查画面漂移。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-shortform-growth",
        prompt=(
            "我有一段横屏短剧要改成竖屏分发，现在前三秒太平，15秒内没有回报，字幕也"
            "没有卡住重音。请做钩子、留存、字幕、CTA和横竖屏重构诊断；没有真实播放"
            "数据时只做结构判断，不要预测涨幅或照抄参考片。"
        ),
        discriminator="平台分发、留存和重构策略，而不是核心剧情分镜或镜头覆盖完整性。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-script-doctor",
        prompt=(
            "我这个短剧剧本先别改，帮我逐场读一遍：哪些地方是客观矛盾、哪些是连续性风险、"
            "哪些只是可选优化，给我一份带编号的诊断清单。看完我挑几条再让你改，改完我确认"
            "了才锁定版本。不要替我补我没写的设定。"
        ),
        discriminator="单部剧本的叙事诊断→授权改稿→版本锁定，而不是跨集事实账本或分镜。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-shotcraft",
        prompt=(
            "第7镜要表现角色逐步意识到自己被包围，我想用一个主运镜、清楚的节拍和声音"
            "落点，并让前后镜的出口入口接得上。请选择具体镜头配方并转成现有视频提示词"
            "合同，不要操作画布或直接生成媒体。"
        ),
        discriminator="单镜运动、节奏、转场和声音落点，而不是完整分镜序列或通用摄影参数。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-story-director",
        prompt=(
            "我只有一个“母亲用假身份保护女儿”的核心创意，想发展成12分钟短剧，需要"
            "主题命题、人物弧光、冲突升级、潜台词和最后反转。请先做剧本方法设计，不要"
            "排镜头、做画面或检查已有剧本连续性。"
        ),
        discriminator="从核心创意发展故事结构，而不是校验既有设定或翻译定稿剧本。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-storyboard",
        prompt=(
            "第3集第5到7场的剧本已经定稿，请把它翻译成逐镜合同：每镜的叙事目的、动作"
            "起止、景别机位、轴线、光线、运镜、声音和视频提示词都要明确。请把方案安全"
            "落到当前画布的完整写入合同，但本轮不要实际写入；不要擅自改剧情，"
            "也不要把画布命令当成媒体生成。"
        ),
        discriminator="把既有剧本翻译成完整逐镜合同，而不是补覆盖素材或只优化单镜工艺。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-style-lock",
        prompt=(
            "我有三张已经通过的参考图，准备用于20个不同主体的镜头，但现在颜色、材质"
            "和光线每张都在变。请把参考里的稳定视觉关系做成风格合同，区分不变项、允许"
            "变量和禁止漂移，再给最小修复方案，未做真实探针前不要判定风格已锁成功。"
        ),
        discriminator="已有批准参考后的跨镜风格合同与漂移修复，而不是先选择画风。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-template-director",
        prompt=(
            "这个产品视频要做首尾帧过渡，我已经有两张关键帧，想确认画布现有起步模板里"
            "有没有匹配的节点骨架。请核对所需输入、角色槽和会产出什么，给出选型与"
            "插入前检查清单；本轮不要实际插入，也不要自动开始生成。"
        ),
        discriminator="在模板目录中选型并插入可编辑骨架，而不是驱动整集持久生产。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-visual-style",
        prompt=(
            "这个故事还没定美术方向，我想比较写实电影感、90年代赛璐珞和暗黑水墨，看看"
            "每种风格要控制哪些媒介、线稿、色板和材质参数。请给选型和混合建议，不要把它"
            "提前说成已经锁定的成片风格，也不要生成测试图。"
        ),
        discriminator="没有唯一批准参考时的画风选择与参数，而不是建立风格合同。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas-workflow-engineering",
        prompt=(
            "我想在本地搭一条可重复的AI电影管线，覆盖文生图、局部重绘、ControlNet、"
            "LoRA堆叠、放大、质量评分和批量处理，还要说明不同模型和成本。请给分阶段"
            "工作流与门禁，但不要声称这些工作流已经运行，也不要把某组采样器或LoRA参数"
            "当成所有模型的通用答案。"
        ),
        discriminator="ComfyUI式生产管线、成熟度和成本设计，而不是产品工程治理或LoRA训练。",
    ),
    SkillRoutingCase(
        skill_name="village-canvas",
        prompt=(
            "我是这个项目的新用户，想先知道当前有哪些剧集、任务做到哪一步、上传过的"
            "剧本是什么。请读取真实项目状态后再回答；这次只做查询和缺口说明，不要改"
            "画布或启动媒体。"
        ),
        discriminator="项目级状态、任务和上传查询，而不是从当前进度驱动整集一键成片。",
    ),
)


__all__ = ["SKILL_ROUTING_CASES", "SkillRoutingCase"]
