"""Browser-local canvas actions exposed through the capability broker.

Each card carries the exact fixed UI action, and the node tools also carry the
mode, operation or tool type the browser must receive. ``ToolSpec`` keeps those
fixed values beside the card instead of in a second capability-to-action map.
"""

from __future__ import annotations

from .spec import ToolSpec


FRONTEND_UI_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        id="canvas.ui.select_node",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "select_node"},
        card={
            "id": "canvas.ui.select_node",
            "domain": "canvas",
            "purpose": "在当前浏览器画布中真实选中指定节点，不修改节点数据。",
            "required_args": ["node_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "search_terms": "选中 节点 浏览器 UI select node",
        },
    ),
    ToolSpec(
        id="canvas.ui.focus_node",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "focus_node"},
        card={
            "id": "canvas.ui.focus_node",
            "domain": "canvas",
            "purpose": "在当前浏览器画布中真实选中并聚焦指定节点。",
            "required_args": ["node_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "search_terms": "聚焦 定位 节点 浏览器 UI focus node",
        },
    ),
    ToolSpec(
        id="canvas.ui.fit_view",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "fit_view"},
        card={
            "id": "canvas.ui.fit_view",
            "domain": "canvas",
            "purpose": "让当前浏览器画布视口真实适配全部节点。",
            "required_args": [],
            "cost": "free",
            "side_effect": "browser_ui",
            "search_terms": "整理 定位 全部节点 适配视口 fit view",
        },
    ),
    ToolSpec(
        id="canvas.ui.open_tool_dialog",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "open_tool_dialog"},
        card={
            "id": "canvas.ui.open_tool_dialog",
            "domain": "canvas",
            "purpose": "打开指定节点的真实工具面板，但不自动执行面板操作。",
            "required_args": ["node_id", "tool_type"],
            "cost": "free",
            "side_effect": "browser_ui",
            "search_terms": "打开 节点 工具 面板 对话框 dialog",
        },
    ),
    ToolSpec(
        id="canvas.ui.close_tool_dialog",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "close_tool_dialog"},
        card={
            "id": "canvas.ui.close_tool_dialog",
            "domain": "canvas",
            "purpose": "关闭当前浏览器画布中已打开的节点工具面板。",
            "required_args": [],
            "cost": "free",
            "side_effect": "browser_ui",
            "search_terms": "关闭 节点 工具 面板 对话框 dialog",
        },
    ),
    ToolSpec(
        id="canvas.node.image.crop",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "open_tool_dialog", "tool_type": "crop"},
        card={
            "id": "canvas.node.image.crop",
            "domain": "canvas",
            "purpose": "在指定图片节点打开真实裁剪构图工具，应用后由前端创建并连接新的图片节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_image_tool",
            "tool_type": "crop",
            "idempotency": "none",
            "verifier_contract": "frontend_tool_dialog_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "图片 裁剪 构图 比例 crop image tool",
        },
    ),
    ToolSpec(
        id="canvas.node.image.annotate",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "open_tool_dialog", "tool_type": "annotate"},
        card={
            "id": "canvas.node.image.annotate",
            "domain": "canvas",
            "purpose": "在指定图片节点打开真实图片标注工具，应用后由前端创建并连接新的标注图片节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_image_tool",
            "tool_type": "annotate",
            "idempotency": "none",
            "verifier_contract": "frontend_tool_dialog_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "图片 标注 画圈 注释 annotate image tool",
        },
    ),
    ToolSpec(
        id="canvas.node.storyboard.split_input",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={
            "action": "open_tool_dialog",
            "tool_type": "split-storyboard",
        },
        card={
            "id": "canvas.node.storyboard.split_input",
            "domain": "canvas",
            "purpose": "在指定宫格图片节点打开真实分格抽取工具，应用后由前端创建并连接分镜节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_image_tool",
            "tool_type": "split-storyboard",
            "idempotency": "none",
            "verifier_contract": "frontend_tool_dialog_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "宫格 九宫格 分镜 分格 抽取 storyboard split grid",
        },
    ),
    ToolSpec(
        id="canvas.node.video.capture_first_frame",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_capture_frame", "mode": "first"},
        card={
            "id": "canvas.node.video.capture_first_frame",
            "domain": "canvas",
            "purpose": "从指定视频节点真实截取首帧，并创建自动连回源节点的图片节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_capture_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 首帧 截取 当前帧 图片 frame capture first video",
        },
    ),
    ToolSpec(
        id="canvas.node.video.capture_last_frame",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_capture_frame", "mode": "last"},
        card={
            "id": "canvas.node.video.capture_last_frame",
            "domain": "canvas",
            "purpose": "从指定视频节点真实截取尾帧，并创建自动连回源节点的图片节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_capture_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 尾帧 截取 frame capture last video",
        },
    ),
    ToolSpec(
        id="canvas.node.video.capture_current_frame",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_capture_frame", "mode": "current"},
        card={
            "id": "canvas.node.video.capture_current_frame",
            "domain": "canvas",
            "purpose": "从指定视频节点当前播放位置真实截取画面，并创建自动连回源节点的图片节点。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_capture_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 当前帧 截取 frame capture current video",
        },
    ),
    ToolSpec(
        id="canvas.node.video.clip",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_set_operation", "operation": "clip"},
        card={
            "id": "canvas.node.video.clip",
            "domain": "canvas",
            "purpose": "在指定视频节点打开真实片段截取编辑器，不伪造已提交剪辑。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_operation_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 片段 截取 剪辑 clip editor video",
        },
    ),
    ToolSpec(
        id="canvas.node.video.subtitle_erase_smart",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={
            "action": "video_set_operation",
            "operation": "subtitle-smart",
        },
        card={
            "id": "canvas.node.video.subtitle_erase_smart",
            "domain": "canvas",
            "purpose": "在指定视频节点打开智能去字幕模式，等待用户确认后再提交处理。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_operation_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 智能 去字幕 subtitle erase smart",
        },
    ),
    ToolSpec(
        id="canvas.node.video.subtitle_erase_box",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={
            "action": "video_set_operation",
            "operation": "subtitle-box",
        },
        card={
            "id": "canvas.node.video.subtitle_erase_box",
            "domain": "canvas",
            "purpose": "在指定视频节点打开框选去字幕模式，等待区域选择后再提交处理。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_operation_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 框选 去字幕 subtitle erase box",
        },
    ),
    ToolSpec(
        id="canvas.node.video.download",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_download"},
        card={
            "id": "canvas.node.video.download",
            "domain": "canvas",
            "purpose": "在当前浏览器中下载指定视频节点的已完成结果，不修改画布。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["project_id", "source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_action_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 下载 保存 export download video",
        },
    ),
    ToolSpec(
        id="canvas.node.video.fullscreen",
        handler_name="_handle_frontend_ui_tool",
        handler_defaults={"action": "video_fullscreen"},
        card={
            "id": "canvas.node.video.fullscreen",
            "domain": "canvas",
            "purpose": "在当前浏览器查看器中全屏打开指定视频节点，不修改画布。",
            "required_args": ["canvas_id", "node_id"],
            "optional_args": ["project_id", "source_turn_id"],
            "cost": "free",
            "side_effect": "browser_ui",
            "route_policy": "frontend_video_node",
            "idempotency": "none",
            "verifier_contract": "frontend_video_action_receipt.v1",
            "failure_policy": "stop_on_error",
            "resume_policy": "reissue_ui_action",
            "search_terms": "视频 全屏 播放 查看 fullscreen viewer video",
        },
    ),
)
