"""Model-visible order for the Village canvas agent surface.

The order tools and capability cards appear in is a product decision: it is what
the agent reads, and what a search with a row limit returns first. Until T-158 it
was an accident of which of the seven source parts happened to define what, so a
migration could reorder the agent's world without anyone noticing.

These tuples write that decision down once. Editing them alone changes nothing:
`check_agent_tool_surface.py` holds the assembled surface against the frozen
baseline, so every entry still has to come from a `ToolSpec` or from the
not-yet-migrated source parts.
"""

TOOL_ORDER = (
    "village_canvas_get",
    "village_canvas_post",
    "village_canvas_patch",
    "village_canvas_delete",
    "village_canvas_tavily_search",
    "village_canvas_jev_judge",
    "freezone_get_canvas_snapshot",
    "freezone_get_canvas_viewport",
    "village_canvas_get_script_media_readiness",
    "freezone_emit_canvas_command",
    "freezone_propose_generation",
    "freezone_run_node",
    "freezone_retry_node",
    "freezone_stop_task",
    "village_canvas_pipeline_status",
    "village_canvas_story_lab_get",
    "village_canvas_story_lab_save",
    "village_canvas_story_lab_generate",
    "village_canvas_story_lab_publish",
    "village_canvas_get_production_control",
    "village_canvas_list_workflows",
    "village_canvas_list_workflow_runs",
    "village_canvas_start_workflow_run",
    "village_canvas_get_workflow_run",
    "village_canvas_update_workflow_run",
    "village_canvas_command_workflow_run",
    "village_canvas_start_production_run",
    "village_canvas_command_production_run",
    "village_canvas_list_tasks",
    "village_canvas_get_task",
    "village_canvas_get_episode_script",
    "village_canvas_list_ingest_uploads",
    "village_canvas_build_characters",
    "village_canvas_plan_episodes",
    "village_canvas_generate_script",
    "village_canvas_update_character_face_prompt",
    "village_canvas_plan_identities",
    "village_canvas_plan_scenes",
    "village_canvas_plan_props",
    "village_canvas_generate_scene_master",
    "village_canvas_generate_scene_reverse",
    "village_canvas_generate_portrait",
    "village_canvas_generate_identity_image",
    "village_canvas_generate_sketches",
    "village_canvas_detect_sketch_identities",
    "village_canvas_get_sketches",
    "village_canvas_get_first_frames",
    "village_canvas_get_sketch_candidates",
    "village_canvas_get_scene_images",
    "village_canvas_get_character_media",
    "village_canvas_get_episode_media",
    "village_canvas_render_first_frames",
    "village_canvas_generate_audio",
    "village_canvas_optimize_video_global",
    "village_canvas_compose_episode",
    "village_canvas_get_final_video",
    "village_canvas_start_single_video",
    "village_canvas_ui",
    "village_canvas_dispatch_action",
    "village_canvas_read_compact",
    "village_canvas_apply_commands",
    "village_canvas_wait_receipt",
)

CARD_ORDER = (
    "canvas.snapshot",
    "canvas.viewport",
    "canvas.wait_receipt",
    "media.readiness.revalidate",
    "state.sql.schema",
    "state.sql.query",
    "workflow.asset_binding.repair",
    "workflow.asset_binding.revalidate",
    "canvas.ui.select_node",
    "canvas.ui.focus_node",
    "canvas.ui.fit_view",
    "canvas.ui.open_tool_dialog",
    "canvas.ui.close_tool_dialog",
    "canvas.node.image.crop",
    "canvas.node.image.annotate",
    "canvas.node.storyboard.split_input",
    "canvas.node.video.capture_first_frame",
    "canvas.node.video.capture_last_frame",
    "canvas.node.video.capture_current_frame",
    "canvas.node.video.clip",
    "canvas.node.video.subtitle_erase_smart",
    "canvas.node.video.subtitle_erase_box",
    "canvas.node.video.story_analysis",
    "canvas.node.video.upscale",
    "canvas.node.video.audio_separate",
    "canvas.node.video.download",
    "canvas.node.video.fullscreen",
    "camera.image.options",
    "camera.video.templates",
    "camera.resolve",
    "director.scene.compile",
    "research.search",
    "judgment.ask",
    "vision.analyze",
    "task.stop",
    "workflow.list",
    "workflow.runs.list",
    "workflow.run.get",
    "workflow.run.control",
    "pipeline.status",
    "production.control.get",
)
