"""Non-secret model defaults used when no local configuration is present."""

# The standalone product has no inherited vendor gateway. This local fallback
# preserves legacy key-only settings without ever reaching an external vendor;
# the launcher-managed unified route or direct model registry takes precedence.
OFFICIAL_NEWAPI_BASE_URL = "http://127.0.0.1:3000/v1"

DEFAULT_COGNEE_LLM_PROVIDER = "newapi"
DEFAULT_COGNEE_LLM_MODEL = ""
DEFAULT_COGNEE_EMBEDDING_PROVIDER = "newapi"
DEFAULT_COGNEE_EMBEDDING_MODEL = ""
DEFAULT_COGNEE_EMBEDDING_DIM = "1024"
DEFAULT_EMBEDDING_BATCH_SIZE = "10"

DEFAULT_FREEZONE_TRANSLATION_MODEL = ""
DEFAULT_FREEZONE_STORY_SCRIPT_MODEL = ""
DEFAULT_FREEZONE_VISION_MODEL = ""
DEFAULT_VIDEO_PROMPT_OPTIMIZER_MODEL = ""
DEFAULT_FREEZONE_PROMPT_OPTIMIZER_MODEL = ""
DEFAULT_SEEDANCE2_PROMPT_COMPOSER_MODEL = ""

DEFAULT_TEXT_MODEL_BY_ENV = {
    "GLOBAL_VIDEO_OPTIMIZER_MODEL": DEFAULT_VIDEO_PROMPT_OPTIMIZER_MODEL,
    "KEYFRAME_PROMPT_MODEL": DEFAULT_VIDEO_PROMPT_OPTIMIZER_MODEL,
    "SEEDANCE2_PROMPT_COMPOSER_MODEL": DEFAULT_SEEDANCE2_PROMPT_COMPOSER_MODEL,
    "GLOBAL_VIDEO_IDENTITY_DETECTOR_MODEL": "",
    "IDENTITY_PLANNER_CAST_MODEL": "",
    "IDENTITY_PLANNER_ANALYSIS_MODEL": "",
    "IDENTITY_PLANNER_APPEARANCE_MODEL": "",
    "LITERAL_BEAT_META_MODEL": "",
    "SCENE_BUILD_MODEL": "",
    "EPISODE_SCENE_PLANNER_MODEL": "",
    "EPISODE_PROP_PLANNER_MODEL": "",
    "FREEZONE_TRANSLATION_MODEL": DEFAULT_FREEZONE_TRANSLATION_MODEL,
    "FREEZONE_PROMPT_OPTIMIZER_MODEL": DEFAULT_FREEZONE_PROMPT_OPTIMIZER_MODEL,
    "FREEZONE_STORY_SCRIPT_MODEL": DEFAULT_FREEZONE_STORY_SCRIPT_MODEL,
    "FREEZONE_VISION_MODEL": DEFAULT_FREEZONE_VISION_MODEL,
    "STYLE_ANALYZER_MODEL": "",
    "CONTENT_REWRITER_MODEL": "",
    "SCREENPLAY_NORMALIZER_MODEL": "",
    "EPISODE_SCENE_RECONCILE_MODEL": "",
    "NARRATED_SCENE_ASSET_MODEL": "",
    "STAGING_PROP_MODEL": "",
    "COGNEE_LLM_MODEL": DEFAULT_COGNEE_LLM_MODEL,
}
