"""Probe one short H3 dialogue shot with native audio and a voice reference.

The final speech is generated by H3, so mouth motion and audio share one
generation pass.  The supplied audio is only a timbre reference.  This script
is deliberately fail-closed because it performs one paid video generation.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import mimetypes
import re
import sys
import time
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import freezone_full_film_smoke as base  # noqa: E402


ROOT = base.ROOT
ARTIFACT_DIR = base.ARTIFACT_DIR
DEFAULT_VIDEO_MODEL = "direct_video-8b01a39b81951012"
DEFAULT_IMAGE = (
    ROOT
    / "workspace"
    / "artifacts"
    / "freezone-film"
    / "20260917T170132Z-03-storyboard.png"
)


def _stamp() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")


def _project_slug(label: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", str(label or "").casefold()).strip("_")
    return slug[:48] or "native_dialogue"


def _upload_file(
    client: base.RuntimeClient,
    project_id: str,
    path: Path,
    *,
    content_type: str,
) -> str:
    with path.open("rb") as handle:
        response = client.client.post(
            base._project_path(project_id, "freezone/upload"),
            files={"file": (path.name, handle, content_type)},
        )
    payload = base._json(response)
    if response.status_code != 200:
        raise RuntimeError(
            f"upload of {path.name} returned HTTP {response.status_code}: {payload}"
        )
    url = str(base._data(payload).get("url") or "")
    if not url:
        raise RuntimeError(f"upload of {path.name} returned no URL: {payload}")
    return url


async def _make_voice_reference(output_path: Path) -> None:
    import edge_tts

    speech = "雨水落在铁梁上，我看见了那截旧红绳，也听见远处钟摆的声音。"
    communicate = edge_tts.Communicate(
        speech,
        "zh-CN-YunxiNeural",
        rate="-10%",
        pitch="-4Hz",
        volume="+0%",
    )
    await communicate.save(str(output_path))
    if not output_path.exists() or output_path.stat().st_size <= 0:
        raise RuntimeError("failed to create the H3 voice reference")


def _run(args: argparse.Namespace) -> dict[str, Any]:
    if not args.allow_paid_generation:
        raise RuntimeError(
            "paid generation is disabled; pass --allow-paid-generation "
            "to authorize one 5-second H3 dialogue shot"
        )
    image_path = Path(args.image).resolve()
    if not image_path.exists():
        raise RuntimeError(f"reference image does not exist: {image_path}")

    stamp = _stamp()
    label = str(args.output_label or "native-dialogue-probe").strip()
    turns = tuple(
        str(item or "").strip()
        for item in (getattr(args, "turns", None) or (args.text,))
        if str(item or "").strip()
    )
    if not turns:
        raise RuntimeError("native dialogue probe requires at least one spoken turn")
    dialogue_text = "\n".join(turns)
    work_dir = ARTIFACT_DIR / f"{stamp}-{label}"
    work_dir.mkdir(parents=True, exist_ok=True)
    voice_ref_path = work_dir / "lin-mo-voice-reference.mp3"
    if not args.no_voice_reference:
        asyncio.run(_make_voice_reference(voice_ref_path))

    client = base.RuntimeClient(args.base_url, args.timeout_seconds)
    project_id = ""
    receipt: dict[str, Any] = {
        "ok": False,
        "schema": "h3_native_dialogue_probe.v1",
        "startedAt": stamp,
        "videoModel": args.video_model,
        "text": dialogue_text,
        "turns": list(turns),
        "speaker": args.speaker,
        "imagePath": str(image_path),
        "voiceReferencePath": str(voice_ref_path) if not args.no_voice_reference else "",
        "nativeAudio": True,
        "genMode": "allReference",
    }
    try:
        project = base._data(
            client.post(
                "/api/v1/projects",
                json={
                    "name": (
                        f"zz_codex_h3_{_project_slug(label)}_"
                        f"{uuid.uuid4().hex[:12]}"
                    )
                },
            )
        )
        project_id = str(project.get("project_id") or project.get("id") or "")
        if not project_id:
            raise RuntimeError(f"project creation returned no id: {project}")
        image_url = _upload_file(
            client,
            project_id,
            image_path,
            content_type=mimetypes.guess_type(image_path.name)[0] or "image/png",
        )
        references: list[dict[str, str]] = [
            {
                "type": "image",
                "url": image_url,
                "role": "角色参考",
                "label": "林默",
            },
        ]
        if not args.no_voice_reference:
            voice_url = _upload_file(
                client,
                project_id,
                voice_ref_path,
                content_type="audio/mpeg",
            )
            references.append(
                {
                    "type": "audio",
                    "url": voice_url,
                    "role": "音色参考",
                    "label": "林默声线",
                }
            )

        payload = {
            "prompt": args.prompt,
            "references": references,
            "aspect_ratio": "16:9",
            "resolution": "768p",
            "duration_seconds": args.duration,
            "generate_audio": True,
            "generate_audio_explicit": True,
            "dialogue_text": dialogue_text,
            "spoken_dialogue": list(turns),
            "audio_type": "dialogue",
            "speaker": args.speaker,
            "native_audio_strategy": "native",
            "model": args.video_model,
            "model_id": args.video_model,
            "gen_mode": "allReference",
            "canvas_id": f"h3_native_dialogue_{stamp}",
            "node_id": f"h3-native-dialogue-{stamp}",
        }
        started = time.monotonic()
        job = base._data(
            client.post(
                base._project_path(project_id, "freezone/video/omni-gen"),
                json=payload,
            )
        )
        result = base._poll_job(
            client,
            project_id,
            task_type=str(job.get("task_type") or "freezone_video_gen"),
            job_id=str(job.get("job_id") or ""),
            label="H3 native dialogue",
            timeout_seconds=args.generation_timeout,
        )
        video_url = str(result.get("url") or "")
        if not video_url:
            raise RuntimeError(f"H3 result has no URL: {result}")
        output_path = ARTIFACT_DIR / f"{stamp}-{label}.mp4"
        video_bytes, video_sha = base._download(client, video_url, output_path)
        probe = base._probe_video(output_path) if hasattr(base, "_probe_video") else {}
        receipt.update(
            {
                "ok": True,
                "finishedAt": _stamp(),
                "generationSeconds": round(time.monotonic() - started, 2),
                "projectId": project_id,
                "jobId": str(job.get("job_id") or ""),
                "videoUrl": video_url,
                "videoPath": str(output_path),
                "videoBytes": video_bytes,
                "videoSha256": video_sha,
                "probe": probe,
                "runtimeRequestCounts": dict(sorted(client.request_counts.items())),
                "runtimeRequestCountTotal": sum(client.request_counts.values()),
                "runtimeRequestLatencySeconds": {
                    "count": len(client.request_durations),
                    "sum": round(sum(client.request_durations), 6),
                    "p95": round(
                        sorted(client.request_durations)[
                            min(
                                len(client.request_durations) - 1,
                                max(0, int(len(client.request_durations) * 0.95) - 1),
                            )
                        ],
                        6,
                    )
                    if client.request_durations
                    else None,
                },
            }
        )
    finally:
        if project_id and not args.keep_project:
            try:
                client.post(base._project_path(project_id, "delete"))
            except Exception:
                pass

    receipt_path = ARTIFACT_DIR / f"{stamp}-{label}.json"
    receipt_path.write_text(
        json.dumps(receipt, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    receipt["receiptPath"] = str(receipt_path)
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate one short H3 native-dialogue shot."
    )
    parser.add_argument("--base-url", default="http://127.0.0.1:8784")
    parser.add_argument("--video-model", default=DEFAULT_VIDEO_MODEL)
    parser.add_argument("--image", default=str(DEFAULT_IMAGE))
    parser.add_argument("--text", default="这是我姐的。")
    parser.add_argument(
        "--turn",
        action="append",
        default=[],
        help="repeat to provide multiple spoken turns in source order",
    )
    parser.add_argument("--speaker", default="林默")
    parser.add_argument(
        "--prompt",
        default=(
            "雨夜钟楼内部，林默跪在湿滑铁梁上，低头看着掌心的褪色红发带。"
            "他嘴唇自然说话，镜头缓慢前推，人物、服装和雨夜环境保持不变。"
        ),
    )
    parser.add_argument("--output-label", default="native-dialogue-probe")
    parser.add_argument("--no-voice-reference", action="store_true")
    parser.add_argument("--duration", type=int, default=5)
    parser.add_argument("--timeout-seconds", type=float, default=30)
    parser.add_argument("--generation-timeout", type=float, default=1200)
    parser.add_argument("--keep-project", action="store_true")
    parser.add_argument("--allow-paid-generation", action="store_true")
    args = parser.parse_args()
    args.turns = list(getattr(args, "turn", None) or [])
    print(json.dumps(_run(args), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
